version: '3.1'

services:

  wildfly:
    build:
      context: ./build/wildfly
    image: my_wildfly
    container_name: wildfly

    restart: always

    expose:
      - "8080"

    ports:
      - "9990:9990"

    volumes:
      - ./data/wildfly/var/nablarch/format:/var/nablarch/format
      - ./data/wildfly/var/nablarch/output:/var/nablarch/output
      - ./data/wildfly/var/tmp/upload:/var/tmp/upload
    #   - ./data/wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/deployments

  httpd:
    build:
      context: ./build/httpd
    image: my_httpd
    container_name: httpd

    restart: always

    ports:
      - "443:443"

  postgres:
    image: postgres:13
    container_name: postgres

    restart: always

    environment:
      - POSTGRES_PASSWORD=postgres

    expose:
      - "5432"

    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    driver: local
